# Generated by Django 5.2.9 on 2026-09-28 15:52
# Squashed from two migrations generated during PoC development
# (0027_credentialtype_credential + 0028_remove_credential_credential_type_and_more)
# into the final Credential shape directly, since neither ever shipped.
# Filename kept as-is to match already-applied migration state in existing
# local dev databases.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aap_gateway_api', '0026_servicecluster_outlier_detection_local_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('credential_type_name', models.CharField(max_length=512)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='aap_gateway_api.organization')),
            ],
        ),
    ]
